### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by dennismphil** [malipetek/neu-svelte-mac#2]
```
$ npm run build

> neutralino-svelte-macos-app@1.0.0 build
> node build-app.js

(node:52596) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat '/Users/xxxxxx/git/neu-svelte-mac/dist/myapp/myapp-mac_x64'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:52596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:52596) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.  
```

and if I manually create that directory 

```
$ mkdir -p /Users/xxxxxx/git/neu-svelte-mac/dist/myapp/myapp-mac_x64      
```

and rerun ...

```

$ npm run build                                                      

> neutralino-svelte-macos-app@1.0.0 build
> node build-app.js

(node:53721) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat '/Users/xxxxxx/git/neu-svelte-mac/dist/myapp/res.neu'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:53721) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:53721) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
```

Looks like `neu build` has a failure which is causing this

```
$ neu build    
Bundling app...
Generating resources.neu...
TypeError: Cannot read property 'replace' of undefined
    at createAsarFile (/Users/xxxxxx/.volta/tools/image/packages/@neutralinojs/neu/lib/node_modules/@neutralinojs/neu/src/modules/bundler.js:12:56)
    at Object.module.exports.bundleApp (/Users/xxxxxx/.volta/tools/image/packages/@neutralinojs/neu/lib/node_modules/@neutralinojs/neu/src/modules/bundler.js:39:15)
    at Command.<anonymous> (/Users/xxxxxx/.volta/tools/image/packages/@neutralinojs/neu/lib/node_modules/@neutralinojs/neu/src/commands/build.js:11:27)
    at Command.listener [as _actionHandler] (/Users/xxxxxx/.volta/tools/image/packages/@neutralinojs/neu/lib/node_modules/@neutralinojs/neu/node_modules/commander/index.js:922:31)
    at Command._parseCommand (/Users/xxxxxx/.volta/tools/image/packages/@neutralinojs/neu/lib/node_modules/@neutralinojs/neu/node_modules/commander/index.js:1503:14)
    at Command._dispatchSubcommand (/Users/xxxxxx/.volta/tools/image/packages/@neutralinojs/neu/lib/node_modules/@neutralinojs/neu/node_modules/commander/index.js:1443:18)
    at Command._parseCommand (/Users/xxxxxx/.volta/tools/image/packages/@neutralinojs/neu/lib/node_modules/@neutralinojs/neu/node_modules/commander/index.js:1460:12)
    at Command.parse (/Users/xxxxxx/.volta/tools/image/packages/@neutralinojs/neu/lib/node_modules/@neutralinojs/neu/node_modules/commander/index.js:1292:10)
    at Object.<anonymous> (/Users/xxxxxx/.volta/tools/image/packages/@neutralinojs/neu/lib/node_modules/@neutralinojs/neu/bin/neu.js:12:9)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
  _   _            _             _ _             _     
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___ 
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/     
Please check the ./dist directory! 
```

**Comment by dennismphil** [comment]
Fix: Looks like `extensionsPath` is missing in `neutralino.config.json`

```
...
"cli": {
   ...
   "extensionsPath": "",
   ...
}
```

and also in `build-app.js` [line 54](https://github.com/malipetek/neu-svelte-mac/blob/master/build-app.js#L54) `res.neu` -> `resources.neu`

```diff
- await fs.move(path.resolve(process.cwd(), 'dist', appname, 'res.neu'), path.resolve(process.cwd(), `${appname}.app`, 'Contents', 'Resources', 'res.neu'));
+ await fs.move(path.resolve(process.cwd(), 'dist', appname, 'resources.neu'), path.resolve(process.cwd(), `${appname}.app`, 'Contents', 'Resources', 'res.neu'));
```

**Comment by malipetek** [comment]
Looks like `res.neu` was renamed to `resources.neu`. https://github.dev/neutralinojs/neutralinojs-cli
<img width="331" alt="image" src="https://user-images.githubusercontent.com/13527277/158082973-aeb817ec-f5f1-4fdd-adab-5df99f3a4590.png">

**Comment by malipetek** [comment]
https://github.com/malipetek/neu-svelte-mac/commit/bc865578a425424e3e5aba9e1eb130d68e361f6e
